//! Build-time codegen for MITCH constants.
//!
//! Reads `../../ids/*.csv` + `../../bins/*.csv` and emits `$OUT_DIR/constants.rs`.
//! Replaces the previous `build.sh` + committed 3043-LOC `src/constants.rs`.
//! Public surface (`mitch::constants::*`) is preserved.

use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let ids_dir = PathBuf::from(&manifest_dir).join("../../ids");
    let bins_dir = PathBuf::from(&manifest_dir).join("../../bins");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let out_path = PathBuf::from(&out_dir).join("constants.rs");

    // Rerun triggers: any change to source CSVs (per-file for portability).
    println!("cargo:rerun-if-changed=build.rs");
    rerun_dir(&ids_dir);
    rerun_dir(&bins_dir);

    let mut out = String::new();
    out.push_str(HEADER);

    // Enums: AssetClass (from asset-classes.csv) + InstrumentType (from instrument-types.csv).
    let asset_classes = read_csv(&ids_dir.join("asset-classes.csv"));
    let instrument_types = read_csv(&ids_dir.join("instrument-types.csv"));
    emit_enum(&mut out, "AssetClass", &asset_classes);
    emit_enum(&mut out, "InstrumentType", &instrument_types);

    // BinAggregator enum: one variant per bins CSV (sorted by filename, ascending).
    let mut bin_files: Vec<PathBuf> = fs::read_dir(&bins_dir)
        .expect("bins dir read")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("csv"))
        .collect();
    bin_files.sort();

    let bin_variants: Vec<String> = bin_files
        .iter()
        .map(|p| {
            p.file_stem()
                .unwrap()
                .to_string_lossy()
                .replace('-', "_")
                .to_uppercase()
        })
        .collect();

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
    out.push_str("#[allow(non_camel_case_types)]\n");
    out.push_str("pub enum BinAggregator {\n");
    for v in &bin_variants {
        out.push_str(&format!("    {},\n", v));
    }
    out.push_str("}\n\n");

    // DataEntry struct.
    out.push_str(DATA_STRUCT);

    // Data arrays: one per CSV in ids/ (excluding the two enum sources), sorted by filename.
    let mut data_files: Vec<PathBuf> = fs::read_dir(&ids_dir)
        .expect("ids dir read")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("csv"))
        .filter(|p| {
            let stem = p.file_stem().unwrap().to_string_lossy().into_owned();
            stem != "asset-classes" && stem != "instrument-types"
        })
        .collect();
    data_files.sort();

    for f in &data_files {
        emit_data_array(&mut out, f);
    }

    // Resolver impl + convenience functions per data file.
    out.push_str(RESOLVER);
    for f in &data_files {
        emit_convenience_fns(&mut out, f);
    }

    // BINS LazyLock map.
    out.push_str("pub static BINS: LazyLock<HashMap<BinAggregator, [f64; 128]>> = LazyLock::new(|| {\n");
    out.push_str("    let mut main_map = HashMap::new();\n");
    for (i, f) in bin_files.iter().enumerate() {
        let variant = &bin_variants[i];
        let rows = read_csv(f);
        out.push_str("    let bins: [f64; 128] = [\n");
        for r in &rows {
            // bin_id,bin_end — emit bin_end verbatim (numeric).
            let v = r.get(1).map(|s| s.as_str()).unwrap_or("0.0");
            out.push_str(&format!("        {},\n", v));
        }
        out.push_str("    ];\n");
        out.push_str(&format!("    main_map.insert(BinAggregator::{}, bins);\n", variant));
    }
    out.push_str("    main_map\n");
    out.push_str("});\n");

    let mut f = fs::File::create(&out_path).expect("create constants.rs");
    f.write_all(out.as_bytes()).expect("write constants.rs");
}

const HEADER: &str = r#"// Auto-generated by build.rs at compile time. DO NOT EDIT.
use std::collections::HashMap;
use std::sync::LazyLock;

/// Compact macro for DataEntry creation
macro_rules! entry {
    ($id:expr, $name:expr, $aliases:expr) => {
        DataEntry {
            id: $id,
            name: $name,
            aliases: $aliases,
        }
    };
}

"#;

const DATA_STRUCT: &str = r#"/// Standardized data entry: (id, name_lowercase, aliases_lowercase)
#[derive(Debug, Clone)]
pub struct DataEntry {
    pub id: u64,
    pub name: &'static str,
    pub aliases: &'static str,
}

"#;

const RESOLVER: &str = r#"/// Generic resolver that searches both names and aliases
#[derive(Debug)]
pub struct Resolver;

impl Resolver {
    /// Find entity by name or alias (case-insensitive, normalized)
    pub fn find_by_name<'a>(data: &'a [DataEntry], query: &str) -> Option<&'a DataEntry> {
        let normalized_query = Self::normalize(query);

        data.iter().find(|entry| {
            if entry.name == normalized_query {
                return true;
            }
            if !entry.aliases.is_empty() {
                for alias in entry.aliases.split('|') {
                    if alias == normalized_query {
                        return true;
                    }
                }
            }
            false
        })
    }

    /// Find entity by ID
    pub fn find_by_id<'a>(data: &'a [DataEntry], id: u64) -> Option<&'a DataEntry> {
        data.iter().find(|entry| entry.id == id)
    }

    /// Normalize string for comparison (lowercase, alphanumeric only)
    fn normalize(input: &str) -> String {
        input.to_lowercase().chars().filter(|c| c.is_alphanumeric()).collect()
    }
}

"#;

fn rerun_dir(dir: &Path) {
    if let Ok(rd) = fs::read_dir(dir) {
        for e in rd.flatten() {
            let p = e.path();
            if p.is_file() {
                println!("cargo:rerun-if-changed={}", p.display());
            }
        }
    }
    println!("cargo:rerun-if-changed={}", dir.display());
}

/// Minimal CSV parser: skips header row, splits on `,`, trims `\r` + surrounding quotes.
/// Sufficient for the MITCH CSVs which contain no embedded commas or escape sequences.
fn read_csv(path: &Path) -> Vec<Vec<String>> {
    let content = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("read {}: {}", path.display(), e));
    let mut rows = Vec::new();
    for (i, line) in content.lines().enumerate() {
        if i == 0 {
            continue; // header
        }
        let line = line.trim_end_matches('\r');
        if line.is_empty() {
            continue;
        }
        let fields: Vec<String> = line
            .split(',')
            .map(|f| f.trim_matches('"').to_string())
            .collect();
        rows.push(fields);
    }
    rows
}

/// Emit a `pub enum <Name>` + `impl <Name> { pub fn from_id(id: u8) -> Self }`.
/// Source CSV layout: `id, name, aliases`. Variant identifier = column 3 (aliases).
/// Skip rows where column 3 is empty or contains `*` (reserved markers).
fn emit_enum(out: &mut String, name: &str, rows: &[Vec<String>]) {
    let kept: Vec<(&str, &str)> = rows
        .iter()
        .filter_map(|r| {
            let id = r.get(0)?;
            let variant = r.get(2)?;
            if variant.is_empty() || variant.contains('*') {
                return None;
            }
            Some((id.as_str(), variant.as_str()))
        })
        .collect();

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
    out.push_str("#[allow(non_camel_case_types)]\n");
    out.push_str(&format!("pub enum {} {{\n", name));
    for (id, variant) in &kept {
        out.push_str(&format!("    {} = {},\n", variant, id));
    }
    out.push_str("}\n\n");

    let default = kept.first().map(|(_, v)| *v).unwrap_or("");
    out.push_str(&format!("impl {} {{\n", name));
    out.push_str("    pub fn from_id(id: u8) -> Self {\n");
    out.push_str("        match id {\n");
    for (id, variant) in &kept {
        out.push_str(&format!("            {} => Self::{},\n", id, variant));
    }
    out.push_str(&format!("            _ => Self::{}, // Default\n", default));
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

/// Emit `pub static <STEM>_DATA: &[DataEntry] = &[...]` for a data CSV.
/// CSV layout: `id, name, aliases` (aliases is `|`-separated).
/// Name → lowercased verbatim. Aliases → each lowercased + alphanumeric (plus
/// the ticker-significant sigils `+` and `-`), deduped against the lowercased
/// name, rejoined with `|`.
///
/// `+`/`-` are preserved (RCA ROOT1c, 2026-06-01): stripping them collapsed
/// alias "ETH+" → "eth", colliding with bare ETH's alias and making ETH/USDT
/// mis-resolve to "Ethereum Plus" (5701). The SDK resolver's
/// `normalize_asset_name` mirrors this keep-set, and `AssetResolver::load_class`
/// panics on any normalized-name collision across distinct class_ids.
fn emit_data_array(out: &mut String, path: &Path) {
    let stem = path.file_stem().unwrap().to_string_lossy().into_owned();
    let const_name = format!("{}_DATA", stem.replace('-', "_").to_uppercase());
    let rows = read_csv(path);

    out.push_str(&format!("/// {} data: (id, name_lowercase, aliases_lowercase)\n", stem));
    out.push_str(&format!("pub static {}: &[DataEntry] = &[\n", const_name));

    for r in &rows {
        let id = match r.get(0) {
            Some(s) if !s.is_empty() => s.as_str(),
            _ => continue,
        };
        let name_raw = match r.get(1) {
            Some(s) => s.as_str(),
            None => continue,
        };
        if name_raw.is_empty() || name_raw.contains('*') {
            continue;
        }
        let name_lower = name_raw.to_lowercase();

        let aliases_raw = r.get(2).map(|s| s.as_str()).unwrap_or("");
        let mut alias_parts: Vec<String> = Vec::new();
        if !aliases_raw.is_empty() {
            for a in aliases_raw.split('|') {
                let clean: String = a
                    .to_lowercase()
                    .chars()
                    .filter(|c| c.is_ascii_alphanumeric() || *c == '+' || *c == '-')
                    .collect();
                if !clean.is_empty() && clean != name_lower && !alias_parts.contains(&clean) {
                    alias_parts.push(clean);
                }
            }
        }
        let aliases_lower = alias_parts.join("|");

        out.push_str(&format!(
            "    entry!({}, \"{}\", \"{}\"),\n",
            id, name_lower, aliases_lower
        ));
    }
    out.push_str("];\n\n");
}

/// Emit `resolve_<stem>` + `<stem>_by_id` helpers backed by `<STEM>_DATA`.
fn emit_convenience_fns(out: &mut String, path: &Path) {
    let stem = path.file_stem().unwrap().to_string_lossy().into_owned();
    let fn_base = stem.replace('-', "_");
    let const_name = format!("{}_DATA", fn_base.to_uppercase());
    let pretty = stem.replace('-', " ");

    out.push_str(&format!("/// Find {} by name or alias\n", pretty));
    out.push_str(&format!(
        "pub fn resolve_{}(query: &str) -> Option<&'static DataEntry> {{\n",
        fn_base
    ));
    out.push_str(&format!("    Resolver::find_by_name({}, query)\n", const_name));
    out.push_str("}\n\n");

    out.push_str(&format!("/// Find {} by ID\n", pretty));
    out.push_str(&format!(
        "pub fn {}_by_id(id: u64) -> Option<&'static DataEntry> {{\n",
        fn_base
    ));
    out.push_str(&format!("    Resolver::find_by_id({}, id)\n", const_name));
    out.push_str("}\n\n");
}
